### ISSUE TITLE
Milton Coupling Efficiency Question

### ISSUE THREAD

**Issue by tb518** [ur-whitelab/peptide-dashboard#5]
Great initial design of peptide.bio!

I'm interested to cross-check this with some of my own synthesized sequences as I did have some difficulties with a couple of them and managed to figure out some predicted difficult couplings via mass spec.

I would just like to clarify something about the Milton coupling efficiency you have on your site,

When inputting a sequence I input it from N to C terminus however during solid-phase synthesis the peptide is built from the C to N terminus. Does this mean I should look at the graph in reverse order? For example, for a 20 AA sequence, I would first couple amino acid 20 to the resin. Then 19 is added and so on. Is this also how I should read the graph or should I input the sequence in reverse order (C to N terminus) as this is the order of coupling?

**Comment by whitead** [comment]
Hi @tb518 Thanks for reaching out! You're absolutely correct - this was computed backwards in our code (N to C). I've fixed it in latest version. It might be confusing to read - it's still written N to C - but the coupling efficiency is now computed C to N. It is displayed N to C to be consistent. You can see the [code here](https://github.com/ur-whitelab/peptide-dashboard/blob/194cc6e33dd6272b1039154a79bd45d94036a0ec/src/components/results/Milton.vue#L48)

**Comment by whitead** [comment]
Please reopen the issue if you have any more questions about it! Thanks
